apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitment-catalog-ingress
  namespace: fitment-catalog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: fitment-catalog.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fitment-backend-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fitment-frontend-service
                port:
                  number: 80
